name: Terraform_Import

on:
  workflow_dispatch:
    inputs:
      resource_type:
        description: 'The type of resource to import (e.g., aws_instance, aws_security_group, etc.)'
        required: true
      resource_name:
        description: 'The logical name of the resource in Terraform (e.g., hands_on_hcl)'
        required: true        
      resource_id:
        description: 'The ID of the resource to import (e.g., i-0cd5ertb3)'
        required: true
      aws_region:
        description: 'The AWS region where the resource exists (e.g., us-east-1)'
        required: true
        default: 'us-east-1'

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs on a Linux environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2  # Set up Terraform

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: 'Terraform Init'
        run: terraform init
        working-directory: ./import  # Specify the directory containing main.tf

      # Step 5: Dynamically import the resource based on user input
      - name: 'Terraform Import Resource'
        run: |
          terraform import ${{ github.event.inputs.resource_type }}.${{ github.event.inputs.resource_name }} ${{ github.event.inputs.resource_id }}
        working-directory: ./import  

      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: ./import  

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: ./import  

      - name: 'Terraform Show'
        run: terraform show
        working-directory: ./import  

      # Step 8: Upload terraform.tfstate as artifact
      - name: 'Upload terraform.tfstate as artifact'
        uses: actions/upload-artifact@v4.5.0
        with:
          name: terraform-state
          path: ./import/terraform.tfstate  # Path to the state file in the import directory

      # Step 9: Download the artifact 
      - name: 'Download terraform.tfstate artifact'
        uses: actions/download-artifact@v4.1.8
        with:
          name: terraform-state
          path: ./downloaded-artifacts
